# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

facebook_app_id: "1040519062651713"
facebook_app_secret: "65c2f55590d1f7444b75a23908e2c8ce"

S3_BUCKET_NAME: "petshuggytest0"
AWS_ACCESS_KEY_ID: "AKIAIJLJMWPKQHIPBIDA"
AWS_SECRET_ACCESS_KEY: "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"
AWS_REGION: "ap-northeast-1"

# stripe key
STRIPE_CONNECT_CLIENT_ID: "ca_8qtAMbu2599KBdiqCNhDF81nRs9TMNc9"
STRIPE_SECRET_KEY: "sk_test_xbFKHblBSkIf74O7C9XpnLxD"
STRIPE_PUBLISHABLE_KEY: "pk_test_bG6H8Rs3XH75XH90U1LVtudI"